apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  # TODO: Use secret and URI
  POSTGRES_DB: elvengard
  POSTGRES_USER: postgresadmin
  POSTGRES_PASSWORD: S0m3Str0ngP@s5
  POSTGRES_HOST: postgresql
  POSTGRES_PORT: "5432"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: core-config
  labels:
    app: flugel
data:
  # TODO: Use secret
  RELEASE_COOKIE: eXB6dGZmQlhwOUtaTk94bU83MXRwMFpIYnlhRlozQkNQTm5EUFkxNQ==
  REDIS_HOST: redis-master
  SERVICE_NAME: elven-private
