language: elixir
elixir: '1.9.0'
otp_release: '21.0'

cache:
  directories:
  - deps
  - _build

env:
  global:
    - MIX_ENV=test

install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get

services:
  - redis-server

before_script:
  - psql -c "CREATE DATABASE elvengard_dev;" -U postgres
  - psql -c "ALTER USER postgres PASSWORD 'postgres';"

script:
  # Check that code is formatted
  - "mix format --dry-run --check-formatted"
  # Run all tests except pending ones
  - "mix test --exclude pending --trace"
