defmodule WorldServer.Enums.Game.Items do
  @moduledoc """
  TODO: Documentation for WorldServer.Enums.Game.Items
  """

  @spec armor_option_type(atom) :: non_neg_integer
  def armor_option_type(:close_combat_defense), do: 51
  def armor_option_type(:long_range_defense), do: 52
  def armor_option_type(:magical_defense), do: 53
  def armor_option_type(:s_defense_all_percentage), do: 54
  def armor_option_type(:reduced_minor_bleeding), do: 55
  def armor_option_type(:reduced_serious_bleeding), do: 56
  def armor_option_type(:reduced_all_bleeding), do: 57
  def armor_option_type(:reduced_small_blackout), do: 58
  def armor_option_type(:reduced_all_blackout), do: 59
  def armor_option_type(:reduced_hand_of_death), do: 60
  def armor_option_type(:reduced_frozen_chance), do: 61
  def armor_option_type(:reduced_blind_chance), do: 62
  def armor_option_type(:reduced_arrestation_chance), do: 63
  def armor_option_type(:reduced_defense_reduction), do: 64
  def armor_option_type(:reduced_shock_chance), do: 65
  def armor_option_type(:reduced_rigidity_chance), do: 66
  def armor_option_type(:s_reduced_all_negative), do: 67
  def armor_option_type(:on_rest_hp_recovery_percentage), do: 68
  def armor_option_type(:natural_hp_recovery_percentage), do: 69
  def armor_option_type(:on_rest_mp_recovery_percentage), do: 70
  def armor_option_type(:natural_mp_recovery_percentage), do: 71
  def armor_option_type(:s_on_attack_recovery_percentage), do: 72
  def armor_option_type(:reduce_critical_chance), do: 73
  def armor_option_type(:fire_resistance_increase), do: 74
  def armor_option_type(:water_resistance_increase), do: 75
  def armor_option_type(:light_resistance_increase), do: 76
  def armor_option_type(:dark_resistance_increase), do: 77
  def armor_option_type(:s_increase_all_resistance), do: 78
  def armor_option_type(:dignity_loss_reduced), do: 79
  def armor_option_type(:point_consumption_reduced), do: 80
  def armor_option_type(:mini_game_production_increased), do: 81
  def armor_option_type(:food_healing), do: 82
  def armor_option_type(:pvp_defense_percentage), do: 83
  def armor_option_type(:pvp_dodge_close), do: 84
  def armor_option_type(:pvp_dodge_ranged), do: 85
  def armor_option_type(:pvp_dodge_magic), do: 86
  def armor_option_type(:s_pvp_dodge_all), do: 87
  def armor_option_type(:pvp_mp_protect), do: 88
  def armor_option_type(:champion_pvp_ignore_attack_fire), do: 89
  def armor_option_type(:champion_pvp_ignore_attack_water), do: 90
  def armor_option_type(:champion_pvp_ignore_attack_light), do: 91
  def armor_option_type(:champion_pvp_ignore_attack_dark), do: 92
  def armor_option_type(:absorb_damage_percentage_a), do: 93
  def armor_option_type(:absorb_damage_percentage_b), do: 94
  def armor_option_type(:absorb_damage_percentage_c), do: 95
  def armor_option_type(:increase_evasiveness), do: 96

  @spec einfo_packet_type(atom) :: non_neg_integer
  def einfo_packet_type(:weapon_default), do: 0
  def einfo_packet_type(:main_weapon_archer), do: 1
  def einfo_packet_type(:armor), do: 2
  def einfo_packet_type(:hat), do: 3
  def einfo_packet_type(:jewelery), do: 4
  def einfo_packet_type(:main_weapon_magician), do: 5
  def einfo_packet_type(:specialist), do: 8

  @spec equipment_option_type(atom) :: non_neg_integer
  def equipment_option_type(:shell), do: 0
  def equipment_option_type(:jewel_perfection), do: 1

  @spec equipment_type(atom) :: non_neg_integer
  def equipment_type(:main_weapon), do: 0
  def equipment_type(:armor), do: 1
  def equipment_type(:hat), do: 2
  def equipment_type(:gloves), do: 3
  def equipment_type(:boots), do: 4
  def equipment_type(:secondary_weapon), do: 5
  def equipment_type(:necklace), do: 6
  def equipment_type(:ring), do: 7
  def equipment_type(:bracelet), do: 8
  def equipment_type(:mask), do: 9
  def equipment_type(:fairy), do: 10
  def equipment_type(:amulet), do: 11
  def equipment_type(:sp), do: 12
  def equipment_type(:costume_suit), do: 13
  def equipment_type(:costume_hat), do: 14
  def equipment_type(:weapon_skin), do: 15

  @spec inventory_type(atom) :: non_neg_integer
  def inventory_type(:equipment), do: 0
  def inventory_type(:main), do: 1
  def inventory_type(:etc), do: 2
  def inventory_type(:miniland), do: 3
  def inventory_type(:specialist), do: 6
  def inventory_type(:costume), do: 7
  def inventory_type(:wear), do: 8
  def inventory_type(:bazaar), do: 9
  def inventory_type(:warehouse), do: 10
  def inventory_type(:family_ware_house), do: 11
  def inventory_type(:pet_warehouse), do: 12
  def inventory_type(:partner_inventory), do: 13

  @spec class_type(atom) :: non_neg_integer
  def class_type(:unknown1), do: 1
  def class_type(:unknown2), do: 2
  def class_type(:unknown4), do: 4
  def class_type(:unknown8), do: 8

  @spec type(atom) :: non_neg_integer
  def type(:weapon), do: 0
  def type(:armor), do: 1
  def type(:fashion), do: 2
  def type(:jewelery), do: 3
  def type(:specialist), do: 4
  def type(:box), do: 5
  def type(:shell), do: 6
  def type(:main), do: 10
  def type(:upgrade), do: 11
  def type(:production), do: 12
  def type(:map), do: 13
  def type(:special), do: 14
  def type(:potion), do: 15
  def type(:event), do: 16
  def type(:quest1), do: 18
  def type(:sell), do: 20
  def type(:food), do: 21
  def type(:snack), do: 22
  def type(:magical), do: 24
  def type(:part), do: 25
  def type(:teacher), do: 26
  def type(:ammo), do: 27
  def type(:quest2), do: 28
  def type(:house), do: 30
  def type(:garden), do: 31
  def type(:minigame), do: 32
  def type(:terrace), do: 33
  def type(:miniland_theme), do: 34

  @spec wear_type(atom) :: non_neg_integer
  def wear_type(:player), do: 0
  def wear_type(:partner), do: 1

  @spec jewel_option_type(atom) :: non_neg_integer
  def jewel_option_type(:hp), do: 0
  def jewel_option_type(:mp), do: 1
  def jewel_option_type(:hp_recovery), do: 2
  def jewel_option_type(:mp_recovery), do: 3
  def jewel_option_type(:mp_consumption), do: 4
  def jewel_option_type(:critical_damage_decrease), do: 5

  @spec weapon_option_level_type(atom) :: non_neg_integer
  def weapon_option_level_type(:c), do: 0
  def weapon_option_level_type(:b), do: 1
  def weapon_option_level_type(:a), do: 2
  def weapon_option_level_type(:s), do: 3

  @spec weapon_option_type(atom) :: non_neg_integer
  def weapon_option_type(:increase_damage), do: 1
  def weapon_option_type(:s_damage_percentage), do: 2
  def weapon_option_type(:minor_bleeding), do: 3
  def weapon_option_type(:bleeding), do: 4
  def weapon_option_type(:serious_bleeding), do: 5
  def weapon_option_type(:blackout), do: 6
  def weapon_option_type(:frozen), do: 7
  def weapon_option_type(:deadly_blackout), do: 8
  def weapon_option_type(:increase_damage_on_plants), do: 9
  def weapon_option_type(:increase_damage_on_animals), do: 10
  def weapon_option_type(:increase_damage_on_demons), do: 11
  def weapon_option_type(:increase_damages_on_zombies), do: 12
  def weapon_option_type(:increase_damages_on_small_animals), do: 13
  def weapon_option_type(:s_damage_percentage_on_giant_monsters), do: 14
  def weapon_option_type(:increase_crit_chance), do: 15
  def weapon_option_type(:increase_crit_damages), do: 16
  def weapon_option_type(:protect_wand_skill_interruption), do: 17
  def weapon_option_type(:increase_fire_element), do: 18
  def weapon_option_type(:increase_water_element), do: 19
  def weapon_option_type(:increase_light_element), do: 20
  def weapon_option_type(:increase_darkness_element), do: 21
  def weapon_option_type(:s_increase_all_elements), do: 22
  def weapon_option_type(:reduce_mp_consumption), do: 23
  def weapon_option_type(:hp_regeneration_on_kill), do: 24
  def weapon_option_type(:mp_regeneration_on_kill), do: 25
  def weapon_option_type(:attack_sl), do: 26
  def weapon_option_type(:defense_sl), do: 27
  def weapon_option_type(:element_sl), do: 28
  def weapon_option_type(:hp_mp_sl), do: 29
  def weapon_option_type(:s_global_sl), do: 30
  def weapon_option_type(:gold_percentage), do: 31
  def weapon_option_type(:xp_percentage), do: 32
  def weapon_option_type(:job_xp_percentage), do: 33
  def weapon_option_type(:pvp_damage_percentage), do: 34
  def weapon_option_type(:pvp_enemy_defense_decreased), do: 35
  def weapon_option_type(:pvp_resistance_decreased_fire), do: 36
  def weapon_option_type(:pvp_resistance_decreased_water), do: 37
  def weapon_option_type(:pvp_resistance_decreased_light), do: 38
  def weapon_option_type(:pvp_resistance_decreased_dark), do: 39
  def weapon_option_type(:pvp_resistance_decreased_all), do: 40
  def weapon_option_type(:pvp_always_hit), do: 41
  def weapon_option_type(:pvp_damage_probability_percentage), do: 42
  def weapon_option_type(:pvp_withdraw_mp), do: 43
  def weapon_option_type(:pvp_ignore_resistance_fire), do: 44
  def weapon_option_type(:pvp_ignore_resistance_water), do: 45
  def weapon_option_type(:pvp_ignore_resistance_light), do: 46
  def weapon_option_type(:pvp_ignore_resistance_dark), do: 47
  def weapon_option_type(:regen_specialist_point_per_kill), do: 48
  def weapon_option_type(:increase_precision), do: 49
  def weapon_option_type(:increase_concentration), do: 50
end
